[project]
name = "super-heavy-simulation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.9.2",
    "pygame>=2.6.1",
    "svgpathtools>=1.6.1",
    "svgwrite>=1.4.3",
]
